CI: Test prerelease Python

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -77,8 +77,9 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     strategy:
+      fail-fast: false
       matrix:
-        python-version: ["3.10", "3.11", "3.12", "3.13"]
+        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
 
     steps:
     - uses: actions/checkout@v4
@@ -87,7 +88,15 @@ jobs:
       uses: actions/setup-python@v5
       with:
         python-version: ${{ matrix.python-version }}
+        allow-prereleases: true
         cache: "pip"
+
+    - name: Get Python info
+      id: setup
+      run: |
+        python -m pip install --upgrade pip
+        python --version
+        python .github/utils/get-python-info.py
 
     - name: Download build artifacts
       uses: actions/download-artifact@v4
@@ -97,18 +106,30 @@ jobs:
 
     - name: Install distribution and test dependencies
       run: |
-        python -m pip install --upgrade pip
-        WHEEL="$(ls ./dist/*.whl)"
-        if [ -z "$WHEEL" ]; then
-          echo "No dist/*.whl found"
-          exit 1
-        fi
-        echo $WHEEL
-        python -m pip install "${WHEEL}[test]"
+        wheels=(./dist/*.whl)
+        case ${#wheels[@]} in
+          1)
+            echo "Installing from ${wheels[0]}"
+            python -m pip install "${wheels[0]}[test]"
+            ;;
+          0)
+            echo "Error: No .whl files found in ./dist"
+            exit 1
+            ;;
+          *)
+            echo "Error: Multiple .whl files found in ./dist:"
+            for file in "${wheels[@]}"; do
+              echo "  $file"
+            done
+            exit 1
+            ;;
+        esac
 
     - name: Run tests
+      # Ignore failures in pre-beta Python builds
+      continue-on-error: ${{ steps.setup.outputs.python-release-level == 'alpha' }}
       run: |
-        python tests
+        python -m unittest
 
   publish:
     needs: [lint, build, test]
